# Generated by Django 4.2.1 on 2024-11-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=50, verbose_name='National Identity Number (NIN)')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('job_title', models.CharField(max_length=100)),
                ('average_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.CharField(max_length=20)),
                ('identification', models.CharField(max_length=100, verbose_name='Means of Identification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
